### ISSUE TITLE
Recommended handling of WARNINGs

### ISSUE THREAD

**Issue by wtroddy** [actigraph/pygt3x#43]
Hi there, 

When I'm processing GT3X files with this package I'm seeing the logger catches two warnings: 
- `Event checksum does not match at {timestamp}`
- `1 duplication accelerometer records removed`

I saw there is some discussion about this in #40 and #41 but I'm not 100% certain I completely understand the issue and the fix implemented. I understand the checksum issue may be related to the duplicate record issue, but I don't get them as a pair 100% of the time. There are situations where I only get one or the other, and in some cases I have many (>150) check sum errors without a duplicate error.

I'm wondering what is the "best practice" around this? Are you raising the `WARNING` and we should assume the reader has handled the exception correctly or do we need to be cautious in using this data? 

Thanks for your help,
Will

**Comment by rouzbeh** [comment]
Hi,

The two issues aren't necessarily related. When a record with a bad checksum is found, it is automatically discarded. If duplicated records are found, only one is kept. We do raise WARNING because we want to let you know e.g. when you get fewer records than what you expected. But you shouldn't have to do anything.

Ali

**Comment by wtroddy** [comment]
Okay thank you! I appreciate the clarification.
